[project]
name = "1-expense-tracker-mcp-server"
version = "0.1.0"
description = "Changes for Expense tracker"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.12.4",
]
